
FROM node:18-bullseye

ENV TZ=Asia/Tehran
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tzdata curl git telnet \
      build-essential python3 make g++ \
      libvips-dev libcairo2-dev libjpeg-dev \
      libpango1.0-dev libgif-dev libpng-dev \
      libpixman-1-dev && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN npm install -g pnpm

WORKDIR /opt/app
